name: "external API Action"

description: "use an external API to restreive and display a joke"

outputs:
  joke-output:
    description: The resulting joke from the icanhazdadjokes API

runs:
  using: "node12"
  main: "main.js"
